<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Profile Manage</title>
  <?php echo $this->headLink()->appendStylesheet('/css/bootstrap/css/bootstrap.min.css') ?>
  <?php echo $this->headLink()->appendStylesheet('/css/font-awesome.min.css') ?>
  <?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>
</head>
<body>
<?php echo $this->layout()->content ?>
    <?php 
    
    // adding scripts
    
    echo $this->headScript()->appendFile('/js/jquery.min.js', 'text/javascript');
    echo $this->headScript()->appendFile('/css/bootstrap/js/bootstrap.min.js', 'text/javascript');
    echo $this->headScript()->appendFile('/js/me.js', 'text/javascript');

    ?>

</body>
</html>
